### ISSUE TITLE
Disabled dates demos

### ISSUE THREAD

**Issue by alfredkorn** [benitolopez/hotel-datepicker#2]
On your demo page, on the "Disable some dates" demo you have six(6) initial dates that are disabled on the calendar. There are two minor issues.

1. Issue Type: BUG
When you click/select any **first** date, the closest disabled date BEFORE the date you clicked/selected is no longer disabled and can now be selected. This can lead to a user choosing an unavailable date.

For example: If Aug 7th, 8th, and 9th are disabled, clicking on any date greater than Aug 9th will make Aug 9th available.

2. Issue Type: UI/UX
When you click/select your first date you are stuck with that date. It would be more user friendly if clicking again on that date clears the date if no other date is selected.

These two issues are present with or without "enableCheckout: true"

Other than that, fantastic work!

**Comment by benitolopez** [comment]
​Hi,

1) Can’t reproduce this issue. Are you sure? What browser are you using?

For example, in my demo July 28th is disabled. If you click on July 29th, July 28th is still disabled.

2) Yes, a second click can be useful. But you can still click on another date to make a new selection. I will try to add also that ability in the next weeks. But I don’t have an ETA for that.

**Comment by alfredkorn** [comment]
Thanks for the reply,
Yes I'm sure. I am on a PC using Chrome (latest build).

Can you view this screen recording of your demo page?
https://drive.google.com/file/d/0B-A4Gcu4mVkGTzZjUFp5RHJLakk/view?usp=drivesdk

**Comment by alfredkorn** [comment]
Sorry, use this link:
https://drive.google.com/file/d/0B-A4Gcu4mVkGTzZjUFp5RHJLakk/view?usp=sharing

**Comment by benitolopez** [comment]
Again, I can't reproduce the issue. This doesn't happen on my end. I think that there is a problem with the time zone. What's your time zone?

Also, do you have the same problem with other browsers? And maybe with other PCs or phones?

**Comment by Zuganov** [comment]
I'm facing the same problem here. I think that the problem is related to timezone differences. My timezone is GMT(-03:00). 

As you can see in the in the screen record below, when you select October 15th, next date becomes invalid. 
It happens on Chrome latest build : https://www.screencast.com/t/UNv9rCEXET

Firefox October has two 14th days.
Firefox problem: https://www.screencast.com/t/EPvJiCBinN

**Comment by benitolopez** [comment]
Yes I think that it something related to the time zone. I need some time to make some tests.

@Zuganov I don't have flash installed. Can you use another service to share your videos? I'm interested on the Firefox issue.

**Comment by benitolopez** [comment]
It should be solved now, check the demo.

**Comment by Zuganov** [comment]
@benitolopez Sorry for the late response. Some demos are ok now, but the problem still in the other ones. 
"Default settings with an empty input", "Custom format: DD-MM-YYYY" are examples that is working perfect. But "Default settings with a predefined value in the input" and "Disable some dates: [2017-08-09, 2017-08-05, 2017-08-08, 2017-08-10, 2017-08-13, 2017-08-23]" the problem still.

Great work man, keep it up!

**Comment by benitolopez** [comment]
@Zuganov Are you sure? Checked again and it is working. Did you clear the cache of your browser?

Also, the second example of the disabled dates allows the checkout on a disable date. Can you share some screenshots?

**Comment by Zuganov** [comment]
Here is the screen of the problem on Firefox: https://drive.google.com/file/d/0B67fw3Evy6kXMTFHN3BHMXhSejQ/view?usp=sharing
Chrome: https://www.screencast.com/t/DAqaeHTwyfr

Yes, i cleaned the browser cache. Are you able to watch the video? I tried to convert it but the result wasn't good.

**Comment by benitolopez** [comment]
Sorry but what's the problem on the disabled dates. I see all correctly in your video.

**Comment by Zuganov** [comment]
Yes, the disabled dates are ok. I missunderstood the concept, sorry about that. But, the problem is not related to disabled dates in the other cenarios.

**Comment by benitolopez** [comment]
So there are two problems:
- 16 oct on the first input
- 15 oct with firefox

When did you make the video and the screenshot? Do you remember the exact time? Do you see the same problem now?

**Comment by Zuganov** [comment]
Exactly. These are the problems. The video was made today, somenthing around 30 - 40min ago. Yes, the problem remains, i just tried out again.

**Comment by benitolopez** [comment]
Unfortunately, I can't replicate the issue. I'm using your timezone now (GMT-3) but all works correctly on Firefox and Chrome. Mac and Windows.

Can you check in the next days a few times per day and note the results and the time?

**Comment by Zuganov** [comment]
I can do that. But is really simple to test that issue. How did you change your timezone? Using Windows 10, I changed the timezone to UTC going into date and time configurations and everything works fine. Changing back to (GMT -3) and refreshing the Chrome the error returns.

**Comment by benitolopez** [comment]
I've done the same thing. Yesterday and 10 minutes ago. And I don't see any difference (Chrome and Firefox). Tried with (GMT -3) and with (GMT -3) + light saving.

What's the exact location you choose in the dropdown? Do you have the same problem with other locations in the same fuse (GMT -3)?

Probably the problem is not related to the timezone, but to the light saving.

By the way, do you still having the issue on the same days? (16 oct first input, 15 oct all inputs with firefox)

**Comment by Zuganov** [comment]
To make it works i selected (UTC) Universal Coordinated Time and to make it wrong i select (UTC -03:00) Brasília. Its funny because i tried other locations and it just bug when i select the (UTC -03:00) Brasília.

**Comment by benitolopez** [comment]
Yes, with Brasilia I have the same problem. It happens the 15th of October because there will be a daylight saving time change [that day](https://www.timeanddate.com/time/zone/brazil/brasilia).

This is a big problem because Javascript dates are not perfect. I will try to find a solution in my spare time but I don't know if I will find it. I hope :)

**Comment by benitolopez** [comment]
It should be fixed now.

**Comment by Zuganov** [comment]
Thank you for all the effort on this issue man, it looks perfect now.
